# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [1]:
import numpy as np


# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11,2) # (start number, end number, step count)

array([0, 3, 6, 9])

### zeros and ones

Generate arrays of zeros or ones

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones(3)

array([1., 1., 1.])

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [18]:
np.linspace(0,10,4) 

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [19]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [23]:
np.random.rand(2)

array([0.13693777, 0.17392058])

In [26]:
np.random.rand(5,5)

array([[0.36773058, 0.37044677, 0.14901913, 0.53496274, 0.75947445],
       [0.68517542, 0.40840229, 0.05888576, 0.09448593, 0.63983247],
       [0.52414064, 0.7820557 , 0.23137727, 0.62141692, 0.7839058 ],
       [0.20765929, 0.62314064, 0.89122792, 0.81459262, 0.35179689],
       [0.40530334, 0.77643752, 0.02725229, 0.70660351, 0.41236371]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [28]:
np.random.randn(2)

array([-0.14348312, -0.44399965])

In [31]:
np.random.randn(5,5)

array([[ 1.22649502, -0.45971199, -0.45992307, -1.03643759, -0.40948707],
       [ 0.0388525 ,  1.41430325,  0.89887664, -1.52265907, -0.60589807],
       [ 0.70052461,  1.35609716, -1.052764  , -1.34139158,  1.92994489],
       [-1.37929342,  1.35918174,  0.18835828,  0.49837474,  1.08477992],
       [-0.83667148, -0.65253335, -0.5128776 , -0.59511734,  0.17256008]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [34]:
np.random.randint(1,100)

6

In [35]:
np.random.randint(1,100,10)

array([34, 59, 21, 20, 52, 93, 93, 55,  1, 84])

## Reshape
Returns an array containing the same data with a new shape.

In [43]:
arr = [1,3,5,6,4,5,7,7,2]
arr = np.array(arr)

In [52]:
arr = arr.reshape(3,3)

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [53]:
arr

array([[1, 3, 5],
       [6, 4, 5],
       [7, 7, 2]])

In [47]:
arr.max()

7

In [74]:
a = np.arange(4).reshape((2,2))

In [75]:
np.max(a, axis=0) 

array([2, 3])

In [50]:
arr.min()

1

## Shape

Shape is an attribute that arrays have (not a method):

In [54]:
# Vector
arr.shape

(3, 3)

In [58]:
arr = [1,3,5,6,4,5,7,7,2,1,3,5,6,4,5,7,7,2,1,3,5,6,4,5,7]
arr = np.array(arr)

In [59]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[1, 3, 5, 6, 4, 5, 7, 7, 2, 1, 3, 5, 6, 4, 5, 7, 7, 2, 1, 3, 5, 6,
        4, 5, 7]])

In [60]:
arr.reshape(1,25).shape

(1, 25)

In [61]:
arr.reshape(25,1)

array([[1],
       [3],
       [5],
       [6],
       [4],
       [5],
       [7],
       [7],
       [2],
       [1],
       [3],
       [5],
       [6],
       [4],
       [5],
       [7],
       [7],
       [2],
       [1],
       [3],
       [5],
       [6],
       [4],
       [5],
       [7]])

In [62]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [63]:
arr.dtype

dtype('int64')