# NumPy Indexing and Selection

In [1]:
import numpy as np

In [5]:
arr = np.arange(1,11)

In [6]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection

In [8]:
arr[7]

8

In [9]:
arr[1:5]

array([2, 3, 4, 5])

In [10]:
arr[0:5]

array([1, 2, 3, 4, 5])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [11]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [12]:
arr = np.arange(0,11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Slicing

In [13]:
slice_of_arr = arr[0:6]

slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [14]:
slice_of_arr[:]=99

slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [15]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [16]:
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**.

In [43]:
arr_2d = np.array(([5,2],[20,12]))

arr_2d

array([[ 5,  2],
       [20, 12]])

In [18]:
arr_2d[1]

array([20, 25, 30])

In [19]:
arr_2d[1][0]

20

In [20]:
arr_2d[1,0]

20

In [21]:
# 2D array slicing
arr_2d[:2,1:]  # [row,column]

array([[10, 15],
       [25, 30]])

In [22]:
arr_2d[2]

array([35, 40, 45])

In [26]:
arr_2d[2,:]

array([35, 40, 45])

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [27]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr <= 4

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [29]:
bool_arr = arr>4

In [30]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [31]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [33]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [34]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])